name: Build release
on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    steps:
    - name: Get current tag
      id: current_tag
      run: |
        eval "$(curl -sL --request GET \
          --url "https://api.github.com/repos/Elegant996/Jackett/tags" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: token ${{ github.token }}" \
          | jq -r '.[0] | "export TAG=\(.name)"')"
        
        echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        echo "VERSION=${TAG//v}" >> $GITHUB_OUTPUT

    - name: Get previous tag
      id: previous_tag
      run: |
        eval "$(curl -sL --request GET \
          --url "https://api.github.com/repos/Elegant996/Jackett/tags" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: token ${{ github.token }}" \
          | jq -r '.[1] | "export TAG=\(.name)"')"
        
        echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        echo "VERSION=${TAG//v}" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Sanitize repo slug
      uses: actions/github-script@v7
      id: repo_slug
      with:
        result-encoding: string
        script: return '${{ github.repository }}'.toLowerCase()
    
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      continue-on-error: true
      id: buildx1
      with:
        build-args: |
          VERSION=${{ steps.env.outputs.VERSION }}
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ steps.env.outputs.VERSION }}
          ghcr.io/${{ steps.repo_slug.outputs.result }}:latest

    # Temp workaround for failed builds
    - name: Wait to retry
      if: steps.buildx1.outcome != 'success'
      run: |
        sleep 60

    # Temp workaround for failed builds
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      if: steps.buildx1.outcome != 'success'
      with:
        build-args: |
          VERSION=${{ steps.env.outputs.VERSION }}
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ steps.env.outputs.VERSION }}
          ghcr.io/${{ steps.repo_slug.outputs.result }}:latest

    - name: ghcr.io Cleanup Action
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        mytoken: ${{ secrets.GITHUB_TOKEN }}
        head-ref: '${{ steps.current_tag.outputs.TAG }}'
        base-ref: '${{ steps.previous_tag.outputs.TAG }}'

    - name: Publish release
      uses: ncipollo/release-action@v1.14.0
      with:
        body: |
          Changes in this Release: 
          ${{ steps.changelog.outputs.changelog }}